version: 2
jobs:
  publish:
    docker:
      - image: node
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build_and_publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master